"""
Email/SMTP integration service.
Sends alert notifications, reports, and test emails via configurable SMTP.
Non-fatal if SMTP is not configured — logs a warning and skips.
"""
import asyncio
import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Optional

from core.config import settings

log = logging.getLogger(__name__)


def _is_configured() -> bool:
    """Check if SMTP settings are configured."""
    return bool(settings.SMTP_HOST and settings.SMTP_PORT)


def get_smtp_status() -> dict:
    """Return current SMTP configuration status."""
    configured = _is_configured()
    return {
        "configured": configured,
        "smtp_host": settings.SMTP_HOST or None,
        "smtp_port": settings.SMTP_PORT or None,
        "smtp_user": settings.SMTP_USER or None,
        "from_email": settings.FROM_EMAIL or None,
        "has_password": bool(settings.SMTP_PASS),
        "status": "ready" if configured else "not_configured",
        "message": (
            "SMTP is configured and ready to send."
            if configured
            else "SMTP is not configured. Set SMTP_HOST, SMTP_PORT, and optionally "
                 "SMTP_USER, SMTP_PASS, FROM_EMAIL in your .env file."
        ),
    }


async def send_email(
    to: str,
    subject: str,
    body_html: str,
    from_addr: Optional[str] = None,
) -> dict:
    """
    Send an email via SMTP.
    Returns {"sent": True/False, "message": ...}.
    Non-fatal if SMTP is not configured.
    """
    if not _is_configured():
        log.warning("SMTP not configured — skipping email to %s: %s", to, subject)
        return {"sent": False, "message": "SMTP not configured"}

    sender = from_addr or settings.FROM_EMAIL or f"noreply@{settings.SMTP_HOST}"

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = sender
    msg["To"] = to
    msg.attach(MIMEText(body_html, "html"))

    def _blocking_send() -> None:
        """All smtplib calls are blocking socket I/O — keep them in a worker thread."""
        if settings.SMTP_PORT == 465:
            server = smtplib.SMTP_SSL(settings.SMTP_HOST, settings.SMTP_PORT, timeout=15)
        else:
            server = smtplib.SMTP(settings.SMTP_HOST, settings.SMTP_PORT, timeout=15)
            server.ehlo()
            if settings.SMTP_PORT == 587:
                server.starttls()
                server.ehlo()

        try:
            if settings.SMTP_USER and settings.SMTP_PASS:
                server.login(settings.SMTP_USER, settings.SMTP_PASS)
            server.sendmail(sender, [to], msg.as_string())
        finally:
            # .quit() can itself block; guarantee the socket closes even on error.
            try:
                server.quit()
            except Exception:
                pass

    try:
        # Run the blocking SMTP dialog off the event loop so slow/unreachable
        # mail servers cannot freeze all async request handlers.
        await asyncio.to_thread(_blocking_send)
        log.info("Email sent to %s: %s", to, subject)
        return {"sent": True, "message": f"Email sent to {to}"}
    except Exception as e:
        log.error("Failed to send email to %s: %s", to, e)
        return {"sent": False, "message": f"SMTP error: {str(e)}"}


async def send_alert_notification(user_email: str, alert_data: dict) -> dict:
    """Send an alert notification email."""
    rule_name = alert_data.get("rule", {}).get("name", "Unknown Rule")
    match_count = alert_data.get("match_count", 0)

    subject = f"[Medicaid Inspector] Alert: {rule_name} — {match_count} matches"

    providers_html = ""
    for p in alert_data.get("matching_providers", [])[:10]:
        providers_html += (
            f"<tr>"
            f"<td style='padding:4px 8px'>{p.get('npi','')}</td>"
            f"<td style='padding:4px 8px'>{p.get('provider_name','')}</td>"
            f"<td style='padding:4px 8px'>{p.get('state','')}</td>"
            f"<td style='padding:4px 8px'>{p.get('risk_score',0):.1f}</td>"
            f"<td style='padding:4px 8px'>${p.get('total_paid',0):,.2f}</td>"
            f"</tr>"
        )

    body_html = f"""
    <html><body style="font-family:sans-serif; color:#333;">
    <h2>Alert Triggered: {rule_name}</h2>
    <p><strong>{match_count}</strong> provider(s) matched this alert rule.</p>
    <table border="1" cellspacing="0" style="border-collapse:collapse; margin:16px 0;">
      <tr style="background:#f0f0f0;">
        <th style="padding:4px 8px">NPI</th>
        <th style="padding:4px 8px">Name</th>
        <th style="padding:4px 8px">State</th>
        <th style="padding:4px 8px">Risk Score</th>
        <th style="padding:4px 8px">Total Paid</th>
      </tr>
      {providers_html}
    </table>
    <p style="color:#888; font-size:12px;">
      Generated by Medicaid Fraud Inspector
    </p>
    </body></html>
    """

    return await send_email(user_email, subject, body_html)


async def send_report(user_email: str, report_html: str) -> dict:
    """Send an investigation report via email."""
    subject = "[Medicaid Inspector] Investigation Report"
    return await send_email(user_email, subject, report_html)
